name: 'chatraghu_dbt'
version: '1.0.0'
config-version: 2

profile: 'chatraghu_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  chatraghu_dbt:
      +materialized: view

# Pricing configuration for different model versions
vars:
  # i1.0.0 pricing (per million tokens)
  i1_0_0_prompt_price: 0.4
  i1_0_0_completion_price: 1.6
  
  # i1.0.1 pricing (per million tokens)
  i1_0_1_graph_prompt_price: 0.15
  i1_0_1_eval_prompt_price: 0.04
  i1_0_1_graph_completion_price: 0.6
  i1_0_1_eval_completion_price: 0.15
